site_name: theroyakash algorithms
site_url: https://algorithms.theroyakash.com
repo_url: https://github.com/theroyakash/algorithms.theroyakash.com
edit_uri: ""
repo_name: Star on GitHub

nav:
  - Getting Started:
    - Introduction: index.md
    - Freebies: freebies.md
    - Blind 75 Problems: ./blind75.md
    - Standard Input Output: ./stdinout-usage.md
  - Linear Data Structures:
    - Arrays, Strings and Linked Lists:
      - Arrays:
        - Intro to Arrays: ./arrays/arrays.md
        - Array Problems: ./arrays/array-problems.md
        - Sliding window problems: ./arrays/sliding-window.md
      - Linked Lists:
        - Linked List STL Usage: ./LinkedLists/stl-usage.md
        - Linked List problems: ./LinkedLists/problems.md
    - Hashing: ./hashing/problems.md
    - Stacks, Queues:
      - Stacks:
        - Stacks Usage: ./stacks/usage.md
        - Stack Problems: ./stacks/problems.md
  - Searching and Sorting:
    - Basics and introduction: ./binary-search/intro.md
    - Binary search problems: ./binary-search/problems.md
  - Tree and Graph based data structures:
    - Trees:
      - Tree Implementation: ./trees/implementation.md
      - Tree Problems: ./trees/problems.md
    - Graphs:
      - Graph Usage: graph/usage.md
      - BFS and DFS: graph/bfs-dfs.md
      - Graph Standard Problems: graph/standard-problems.md
      - Graph Problems: graph/problems.md
      - Disjoint Set Implementation: graph/dsu.md
    - Heaps:
      - Heaps Introduction, STL: ./heaps/heap-pq.md
      - Heap Problems: ./heaps/problems.md
      - Two Heaps Problems: ./2heaps/problems.md
  - Recursion and Dynamic Programming:
    - Recursion:
      - Recursion Introduction: ./recursion/intro.md
      - Recursion, Backtracking, Subset Pattern: ./recursion/problems.md
    - Dynamic Programming:
      - Problems: ./dp/problems.md
      - Knapsack Pattern: ./dp/knapsack.md
  - Greedy Algorithms:
    - Greedy Problems: ./greedy/problems.md

theme:
  name: material
  custom_dir: overrides
  # logo: images/logo.png
  features:
    - navigation.expand
    - search.highlight
    - search.share
    - navigation.top
    - navigation.tabs
  palette:
    primary: white
    accent: red
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - tags

markdown_extensions:
  - tables
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  generator: false
  analytics:
    provider: google
    property: G-QZBMGS6591
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/theroyakash
    - icon: fontawesome/brands/github
      link: https://github.com/theroyakash
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/theroyakash

copyright: Copyright &copy; 2022-2024 theroyakash